name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Upload-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            echo "connected to ec2"

            sudo rm -rf chargingStationFrontend
            # Clone new repository
            sudo git clone https://github.com/vinodmalibbd/chargingStationFrontend /var/www/html
            
            sudo cp chargingStationFrontend/* /var/www/html/index.html