name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Upload-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo rm -rf chargingStationFrontend
            sudo git clone https://github.com/vinodmalibbd/chargingStationFrontend
            cd chargingStationFrontend
            sudo kill -9 $(sudo lsof -t -i:5500)
            sudo nohup http-server -p 5500  > output.log 2>&1 &