name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Upload-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            echo "connected to ec2"

            sudo service nginx stop || true
            
            # Remove previous website files
            sudo rm -rf /var/www/html/*

            rm -rf chargingStationFrontend
            # Clone new repository
            git clone https://github.com/vinodmalibbd/chargingStationFrontend /var/www/html
            
            # Configure Nginx to serve the website
            sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
            server {
                listen 80;
                server_name _;
                root /var/www/html;
                index index.html index.htm;
                location / {
                    try_files \$uri \$uri/ /index.html;
                }
            }
            EOF'

            # Restart Nginx
            sudo service nginx restart