name: CI/CD Pipeline
description: Deploy the chargingStationFrontend to EC2

on:
  push:
    branches:
      - main

jobs:
  Upload-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.3.0  # Specify a specific version
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            echo "connected to ec2"
            sudo rm -rf /var/www/html/*
            sudo rm -rf chargingStationFrontend
            sudo git clone https://github.com/vinodmalibbd/chargingStationFrontend /var/www/html
            
            sudo cp -r chargingStationFrontend/* /var/www/html/
